import { Geist, Geist_Mono, Dancing_Script, Satisfy, Great_Vibes, Sacramento, Allura } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing-script",
  subsets: ["latin"],
});

const satisfy = Satisfy({
  variable: "--font-satisfy",
  subsets: ["latin"],
  weight: "400",
});

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  subsets: ["latin"],
  weight: "400",
});

const sacramento = Sacramento({
  variable: "--font-sacramento",
  subsets: ["latin"],
  weight: "400",
});

const allura = Allura({
  variable: "--font-allura",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  metadataBase: new URL("https://paprly.in"),
  title: "Create Next App",
  description: "Generated by create next app",
  title: "Generate Free Invoice Online | Paperly - Professional Invoice Generator | No Signup Required",
  description: "Generate free invoices online instantly with Paperly. Create professional invoices for freelancers, businesses, and consultants. No signup required. Free invoice generator with templates, GST compliance, and instant sharing.",
  keywords: "generate free invoice, free invoice generator, online invoice maker, professional invoice templates, freelancer invoice, business invoice, GST invoice generator, tax invoice online, invoice software free, billing software, create invoice online, invoice maker free, Indian invoice generator, invoice templates free, instant invoice generator, no signup invoice, drag drop invoice builder, invoice sharing, PDF invoice generator",
  authors: [{ name: "Paperly Team" }],
  creator: "Paperly",
  publisher: "Paperly",
  robots: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
  openGraph: {
    title: "Generate Free Invoice Online | Paperly - Professional Invoice Generator",
    description: "Generate free invoices online instantly with Paperly. Create professional invoices for freelancers, businesses, and consultants. No signup required.",
    type: "website",
    locale: "en_US",
    siteName: "Paperly",
    url: "https://paprly.in",
    images: [
      {
        url: "/final_logo.png",
        width: 512,
        height: 512,
        alt: "Paperly - Professional Invoice Generator Logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Generate Free Invoice Online | Paperly - Professional Invoice Generator",
    description: "Generate free invoices online instantly with Paperly. Create professional invoices for freelancers, businesses, and consultants. No signup required.",
    images: ["/final_logo.png"],
  },
  manifest: "/manifest.json",
  icons: {
    icon: "/final_logo.png",
    apple: "/final_logo.png",
  },
  alternates: {
    canonical: "https://paprly.in",
  },
  other: {
    "google-site-verification": "your-verification-code",
    "msvalidate.01": "your-bing-verification-code",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#1F2937",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* AdSense verification script */}
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4918938808225819"
          crossOrigin="anonymous"
        />
        {/* Optional: Google site verification meta tag */}
        <meta
          name="google-adsense-account" content="ca-pub-4918938808225819"
        />
      </head>
      <body className="bg-white text-gray-900">
        <div className=" mx-auto mx-w-[1]">{children}</div>
      </body>
    </html>
  );
}

  

