import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  title: "Generate Free Invoice Online | Paperly - Professional Invoice Generator | No Signup Required",
  description: "Generate free invoices online instantly with Paperly. Create professional invoices for freelancers, businesses, and consultants. No signup required. Free invoice generator with templates, GST compliance, and instant sharing.",
  keywords: "generate free invoice, free invoice generator, online invoice maker, professional invoice templates, freelancer invoice, business invoice, GST invoice generator, tax invoice online, invoice software free, billing software, create invoice online, invoice maker free, Indian invoice generator, invoice templates free, instant invoice generator, no signup invoice, drag drop invoice builder, invoice sharing, PDF invoice generator",
  authors: [{ name: "Paperly Team" }],
  creator: "Paperly",
  publisher: "Paperly",
  robots: "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
  openGraph: {
    title: "Generate Free Invoice Online | Paperly - Professional Invoice Generator",
    description: "Generate free invoices online instantly with Paperly. Create professional invoices for freelancers, businesses, and consultants. No signup required.",
    type: "website",
    locale: "en_US",
    siteName: "Paperly",
    url: "https://paprly.in",
    images: [
      {
        url: "/final_logo.png",
        width: 512,
        height: 512,
        alt: "Paperly - Professional Invoice Generator Logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Generate Free Invoice Online | Paperly - Professional Invoice Generator",
    description: "Generate free invoices online instantly with Paperly. Create professional invoices for freelancers, businesses, and consultants. No signup required.",
    images: ["/final_logo.png"],
  },
  viewport: "width=device-width, initial-scale=1",
  themeColor: "#1F2937",
  manifest: "/manifest.json",
  icons: {
    icon: "/final_logo.png",
    apple: "/final_logo.png",
  },
  alternates: {
    canonical: "https://paprly.in",
  },
  other: {
    "google-site-verification": "your-verification-code",
    "msvalidate.01": "your-bing-verification-code",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
