// Metadata configuration for different pages
export const pageMetadata = {
  home: {
    title: "Generate Free Invoice Online | Paperly | No Signup Required",
    description: "Generate free invoices online instantly with Paperly. Create professional invoices for freelancers, businesses, and consultants. No signup required. Free invoice generator with templates, GST compliance, and instant sharing.",
    keywords: "generate free invoice, free invoice generator, online invoice maker, professional invoice templates, freelancer invoice, business invoice, GST invoice generator, tax invoice online, invoice software free, billing software, create invoice online, invoice maker free, Indian invoice generator, invoice templates free, instant invoice generator, no signup invoice, drag drop invoice builder, invoice sharing, PDF invoice generator",
    canonical: "https://paprly.in/",
    ogTitle: "Generate Free Invoice Online | Paperly - Professional Invoice Generator",
    ogDescription: "Generate free invoices online instantly with Paperly. Create professional invoices for freelancers, businesses, and consultants. No signup required.",
  },
  about: {
    title: "About Paperly - Professional Document Management Platform | Free Invoice Generator",
    description: "Learn about Paperly - the free document management platform that simplifies invoice creation, contract management, and digital signing for freelancers and businesses. No signup required.",
    keywords: "about paperly, document management platform, free invoice generator, contract management, digital signing, freelancer tools, business software, paperly features, document automation",
    canonical: "https://paprly.in/about",
    ogTitle: "About Paperly - Professional Document Management Platform",
    ogDescription: "Learn about Paperly - the free document management platform that simplifies invoice creation, contract management, and digital signing.",
  },
  signup: {
    title: "Sign Up for Paperly - Create Your Free Account | Professional Document Management",
    description: "Sign up for Paperly and create your free account. Start managing documents, creating invoices, and streamlining your workflow with our professional document management platform.",
    keywords: "sign up paperly, create account, free registration, document management account, invoice generator signup, paperly registration, free document tools account",
    canonical: "https://paprly.in/signup",
    ogTitle: "Sign Up for Paperly - Create Your Free Account",
    ogDescription: "Sign up for Paperly and create your free account. Start managing documents, creating invoices, and streamlining your workflow.",
  },
  "sign-in": {
    title: "Sign In to Paperly - Access Your Document Management Account",
    description: "Sign in to your Paperly account to access your documents, invoices, and manage your workflow. Secure login for document management platform.",
    keywords: "sign in paperly, login paperly, access account, document management login, invoice generator login, paperly login, secure login",
    canonical: "https://paprly.in/sign-in",
    ogTitle: "Sign In to Paperly - Access Your Document Management Account",
    ogDescription: "Sign in to your Paperly account to access your documents, invoices, and manage your workflow.",
  },
  contact: {
    title: "Contact Paperly - Get Support & Help | Professional Document Management",
    description: "Contact Paperly for support, help, or inquiries about our document management platform. Get assistance with invoice generation, contract management, and digital signing features.",
    keywords: "contact paperly, paperly support, help desk, customer service, document management support, invoice generator help, paperly contact information",
    canonical: "https://paprly.in/contact",
    ogTitle: "Contact Paperly - Get Support & Help",
    ogDescription: "Contact Paperly for support, help, or inquiries about our document management platform.",
  },
  contracts: {
    title: "Contract Management & Templates | Paperly - Professional Document Platform",
    description: "Create, manage, and sign professional contracts with Paperly. Access free contract templates, digital signing, and secure document sharing. No signup required.",
    keywords: "contract management, contract templates, digital contracts, contract signing, legal documents, contract generator, free contract templates, digital signing contracts",
    canonical: "https://paprly.in/contracts",
    ogTitle: "Contract Management & Templates | Paperly",
    ogDescription: "Create, manage, and sign professional contracts with Paperly. Access free contract templates, digital signing, and secure document sharing.",
  },
  editor: {
    title: "Document Editor | Paperly - Create Professional Documents Online",
    description: "Use Paperly's professional document editor to create invoices, contracts, and other business documents. Drag-and-drop interface, templates, and instant sharing.",
    keywords: "document editor, online editor, invoice editor, contract editor, document creation, drag drop editor, professional document maker, online document tools",
    canonical: "https://paprly.in/editor",
    ogTitle: "Document Editor | Paperly - Create Professional Documents Online",
    ogDescription: "Use Paperly's professional document editor to create invoices, contracts, and other business documents.",
  },
  template: {
    title: "Invoice Templates | Paperly - Free Professional Invoice Templates",
    description: "Choose from professional invoice templates designed for freelancers, businesses, and consultants. Free invoice templates with customization options. No signup required.",
    keywords: "invoice templates, free invoice templates, professional invoice templates, freelancer invoice templates, business invoice templates, invoice template download, customizable invoice templates",
    canonical: "https://paprly.in/template",
    ogTitle: "Invoice Templates | Paperly - Free Professional Invoice Templates",
    ogDescription: "Choose from professional invoice templates designed for freelancers, businesses, and consultants. Free invoice templates with customization options.",
  },
  "e-sign": {
    title: "E-Signature & Digital Signing | Paperly - Secure Document Signing",
    description: "Sign documents digitally with Paperly's e-signature platform. Secure, legally binding signatures for contracts, invoices, and business documents. Free digital signing.",
    keywords: "e-signature, digital signing, electronic signature, document signing, secure signatures, legal signatures, online signature, digital document signing",
    canonical: "https://paprly.in/e-sign",
    ogTitle: "E-Signature & Digital Signing | Paperly",
    ogDescription: "Sign documents digitally with Paperly's e-signature platform. Secure, legally binding signatures for contracts, invoices, and business documents.",
  },
  help: {
    title: "Help & Support | Paperly - Document Management Guide",
    description: "Get help and support for Paperly's document management platform. Tutorials, FAQs, and guides for invoice creation, contract management, and digital signing.",
    keywords: "paperly help, support guide, tutorials, FAQ, document management help, invoice generator tutorial, contract management guide, digital signing help",
    canonical: "https://paprly.in/help",
    ogTitle: "Help & Support | Paperly - Document Management Guide",
    ogDescription: "Get help and support for Paperly's document management platform. Tutorials, FAQs, and guides.",
  },
  "privacy-policy": {
    title: "Privacy Policy | Paperly - Data Protection & Security",
    description: "Read Paperly's privacy policy to understand how we protect your data and ensure security in our document management platform. Learn about data handling and user privacy.",
    keywords: "privacy policy, data protection, user privacy, security policy, document security, data handling, user data protection, privacy terms",
    canonical: "https://paprly.in/privacy-policy",
    ogTitle: "Privacy Policy | Paperly - Data Protection & Security",
    ogDescription: "Read Paperly's privacy policy to understand how we protect your data and ensure security in our document management platform.",
  },
  testimonials: {
    title: "Customer Testimonials | Paperly - User Reviews & Success Stories",
    description: "Read customer testimonials and success stories from Paperly users. See how freelancers and businesses benefit from our document management platform.",
    keywords: "customer testimonials, user reviews, success stories, paperly reviews, customer feedback, user testimonials, document management reviews",
    canonical: "https://paprly.in/testimonials",
    ogTitle: "Customer Testimonials | Paperly - User Reviews & Success Stories",
    ogDescription: "Read customer testimonials and success stories from Paperly users. See how freelancers and businesses benefit from our platform.",
  },
  feedback: {
    title: "Feedback & Suggestions | Paperly - Help Us Improve",
    description: "Share your feedback and suggestions to help improve Paperly's document management platform. Your input helps us create better tools for freelancers and businesses.",
    keywords: "feedback, suggestions, user feedback, improve paperly, feature requests, user suggestions, document management feedback",
    canonical: "https://paprly.in/feedback",
    ogTitle: "Feedback & Suggestions | Paperly - Help Us Improve",
    ogDescription: "Share your feedback and suggestions to help improve Paperly's document management platform.",
  },
};

// Function to get metadata for a specific page
export function getPageMetadata(pageName) {
  return pageMetadata[pageName] || pageMetadata.home;
}
